# Base image: Node.js
FROM node:18

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY web-server/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port React will run on
EXPOSE 3000

# Start the React development server
CMD ["npm", "start"]
